### ISSUE TITLE
Bibliocraft - Thaumic Wood

### ISSUE THREAD

**Issue by TrinaryBrain** [TrinaryBrain/MagiaNaturalis-PublicArea#3]
>***HuggableCreep***
TrinaryBrain, you'd be my hero if you could add support for bibliocraft .............. you know what im talking bout ;3 sorry bout the huge request kek :L

**Comment by Jhary** [comment]
With the new Bibliocraft this is not longer needed. You can add every texture from all solid blocks in your modded instance to all bibliocraft blocks now :)

**Comment by TrinaryBrain** [comment]
that's actually pretty nice, i looked once into the bibliocraft addons and thought like that is way to much work to just add 2 wood types..

**Comment by Jhary** [comment]
yep exactly. But thats now gone *thumbs up*

**Comment by Zsashas** [comment]
@Jhary How exactly do you make custom Bibliocraft things? I would love to be able to have Silverwoodd or Greatwood Shelves and such, but I have no idea how.

**Comment by Jhary** [comment]
@Zsashas Nuchaz made a spotlight video for that. Watch this and have fun https://youtu.be/5WTa6qwgenE
