### ISSUE TITLE
Geo-Occultism research note not appearing in inventory on server

### ISSUE THREAD

**Issue by Nocty201** [TrinaryBrain/MagiaNaturalis-PublicArea#5]
Not sure if this is a problem with your mod, but I'm not sure where else to start - hoping you can point me in the right direction if need be.

We're running a modified and expanded FTB Infinity pack on a Cauldron server. Modlist here: http://www.technicpack.net/modpack/infinite-mayhem.616077/mods

The research for Geo-Occultism is acting normally (complains about not having paper and tools if you don't, allows you to click it if you do) but when you do click it, the game gives the indication that you've been handed the note and it never appears in the inventory. This is also happening for one of the researches in "Thaumic Machina" ( http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2200956-wip-1-7-10-open-beta-thaumcraft-4-2-addon-thaumic ). Not sure what further information I can offer, but if you need some let me know and I'll do my best to provide it.

Thanks!

**Comment by Unrepentant-Atheist** [comment]
Bug is still present.

**Comment by Nocty201** [comment]
We've just reset our map and in the process of doing so removed "Thaumic Machina". Once I get to the point of researching this I'll check if it's still happening for me.

**Comment by TrinaryBrain** [comment]
i wount fix that issue for 1.7.10-0.1.2 because i'm currently rewritting/updating MN to MC 1.8 and i want to redesign the Geo-Occultism Mechanic. How the new mechanic or design will look like i have no idea. Thats why the port to 1.8 will loose features. I will revisit this issue once i implement this feature again.
